apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-monitor
  template:
    metadata:
      labels:
        app: stream-monitor
    spec:
      serviceAccountName: stream-monitor-sa
      restartPolicy: Always
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
      containers:
      - name: monitor
        image: gcr.io/lagorgeous-helping-hands/stream-monitor:latest
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TWITCH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: twitch-api-credentials
              key: client_id
        - name: TWITCH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: twitch-api-credentials
              key: client_secret
        - name: FPS
          value: ".05"
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            mkdir -p /mnt/nfs/jobs/stream-monitor && \
            /app/monitor.sh 2>&1 | tee /mnt/nfs/jobs/stream-monitor/${POD_NAME}.log
            echo "Sleeping for 60 seconds..."
            sleep 60
          done
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
